name: Build Executables
on: [push] # Runs every time you push code

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Add macos-latest if you want

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: pyinstaller --noconsole --onefile --add-data "al3.png;." --add-data "reveil.mp3;." --add-data "bg.png;." __main__.py

    - name: Build with PyInstaller (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --noconsole --onefile --add-data "al3.png:." --add-data "reveil.mp3:." --add-data "bg.png:." __main__.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: horloge-${{ matrix.os }}
        path: dist/
